// Full country, language and time zone lists (English names).
// Generated once from Intl (Node 26 / ICU) and stored statically so server and browser
// render identical labels.

export const allCountries: string[] = [
  "Afghanistan", "Åland Islands", "Albania", "Algeria", "American Samoa", "Andorra",
  "Angola", "Anguilla", "Antarctica", "Antigua & Barbuda", "Argentina", "Armenia",
  "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
  "Bermuda", "Bhutan", "Bolivia", "Bosnia & Herzegovina", "Botswana", "Bouvet Island",
  "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso",
  "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Caribbean Netherlands",
  "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island",
  "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo - Brazzaville", "Congo - Kinshasa", "Cook Islands",
  "Costa Rica", "Côte d’Ivoire", "Croatia", "Cuba", "Curaçao", "Cyprus",
  "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
  "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
  "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France",
  "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia",
  "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada",
  "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau",
  "Guyana", "Haiti", "Heard & McDonald Islands", "Honduras", "Hong Kong SAR China", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland",
  "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey",
  "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait",
  "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
  "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR China", "Madagascar",
  "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands",
  "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia",
  "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
  "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands",
  "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue",
  "Norfolk Island", "North Korea", "North Macedonia", "Northern Mariana Islands", "Norway", "Oman",
  "Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay",
  "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico",
  "Qatar", "Réunion", "Romania", "Russia", "Rwanda", "Samoa",
  "San Marino", "São Tomé & Príncipe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands",
  "Somalia", "South Africa", "South Georgia & South Sandwich Islands", "South Korea", "South Sudan", "Spain",
  "Sri Lanka", "St. Barthélemy", "St. Helena", "St. Kitts & Nevis", "St. Lucia", "St. Martin",
  "St. Pierre & Miquelon", "St. Vincent & Grenadines", "Sudan", "Suriname", "Svalbard & Jan Mayen", "Sweden",
  "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand",
  "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad & Tobago", "Tunisia",
  "Türkiye", "Turkmenistan", "Turks & Caicos Islands", "Tuvalu", "U.S. Outlying Islands", "U.S. Virgin Islands",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay",
  "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis & Futuna",
  "Western Sahara", "Yemen", "Zambia", "Zimbabwe",
];

export const allLanguages: string[] = [
  "Abkhazian", "Afar", "Afrikaans", "Akan", "Albanian", "Amharic",
  "Arabic", "Aragonese", "Armenian", "Assamese", "Avaric", "Avestan",
  "Aymara", "Azerbaijani", "Bambara", "Bangla", "Bashkir", "Basque",
  "Belarusian", "Bhojpuri", "Bislama", "Bosnian", "Breton", "Bulgarian",
  "Burmese", "Catalan", "Chamorro", "Chechen", "Chinese", "Church Slavic",
  "Chuvash", "Cornish", "Corsican", "Cree", "Croatian", "Czech",
  "Danish", "Divehi", "Dutch", "Dzongkha", "English", "Esperanto",
  "Estonian", "Ewe", "Faroese", "Fijian", "Filipino", "Finnish",
  "French", "Fula", "Galician", "Ganda", "Georgian", "German",
  "Greek", "Guarani", "Gujarati", "Haitian Creole", "Hausa", "Hebrew",
  "Herero", "Hindi", "Hiri Motu", "Hungarian", "Icelandic", "Ido",
  "Igbo", "Indonesian", "Interlingua", "Interlingue", "Inuktitut", "Inupiaq",
  "Irish", "Italian", "Japanese", "Javanese", "Kalaallisut", "Kannada",
  "Kanuri", "Kashmiri", "Kazakh", "Khmer", "Kikuyu", "Kinyarwanda",
  "Komi", "Kongo", "Korean", "Kuanyama", "Kurdish", "Kyrgyz",
  "Lao", "Latin", "Latvian", "Limburgish", "Lingala", "Lithuanian",
  "Luba-Katanga", "Luxembourgish", "Macedonian", "Malagasy", "Malay", "Malayalam",
  "Maltese", "Manx", "Māori", "Marathi", "Marshallese", "Mongolian",
  "Nauru", "Navajo", "Ndonga", "Nepali", "North Ndebele", "Northern Sami",
  "Norwegian", "Norwegian Bokmål", "Norwegian Nynorsk", "Nyanja", "Occitan", "Odia",
  "Ojibwa", "Oromo", "Ossetic", "Pali", "Pashto", "Persian",
  "Polish", "Portuguese", "Punjabi", "Quechua", "Romanian", "Romansh",
  "Rundi", "Russian", "Samoan", "Sango", "Sanskrit", "Sardinian",
  "Scottish Gaelic", "Serbian", "Serbian (Latin)", "Shona", "Sichuan Yi", "Sindhi",
  "Sinhala", "Slovak", "Slovenian", "Somali", "South Ndebele", "Southern Sotho",
  "Spanish", "Sundanese", "Swahili", "Swati", "Swedish", "Tahitian",
  "Tajik", "Tamil", "Tatar", "Telugu", "Thai", "Tibetan",
  "Tigrinya", "Tongan", "Tsonga", "Tswana", "Turkish", "Turkmen",
  "Ukrainian", "Urdu", "Uyghur", "Uzbek", "Venda", "Vietnamese",
  "Volapük", "Walloon", "Welsh", "Western Frisian", "Wolof", "Xhosa",
  "Yiddish", "Yoruba", "Zhuang", "Zulu",
];

/** IANA time zone ids. */
export const allTimeZones: string[] = [
  "UTC",
  "Africa/Abidjan", "Africa/Accra", "Africa/Addis_Ababa", "Africa/Algiers",
  "Africa/Asmera", "Africa/Bamako", "Africa/Bangui", "Africa/Banjul",
  "Africa/Bissau", "Africa/Blantyre", "Africa/Brazzaville", "Africa/Bujumbura",
  "Africa/Cairo", "Africa/Casablanca", "Africa/Ceuta", "Africa/Conakry",
  "Africa/Dakar", "Africa/Dar_es_Salaam", "Africa/Djibouti", "Africa/Douala",
  "Africa/El_Aaiun", "Africa/Freetown", "Africa/Gaborone", "Africa/Harare",
  "Africa/Johannesburg", "Africa/Juba", "Africa/Kampala", "Africa/Khartoum",
  "Africa/Kigali", "Africa/Kinshasa", "Africa/Lagos", "Africa/Libreville",
  "Africa/Lome", "Africa/Luanda", "Africa/Lubumbashi", "Africa/Lusaka",
  "Africa/Malabo", "Africa/Maputo", "Africa/Maseru", "Africa/Mbabane",
  "Africa/Mogadishu", "Africa/Monrovia", "Africa/Nairobi", "Africa/Ndjamena",
  "Africa/Niamey", "Africa/Nouakchott", "Africa/Ouagadougou", "Africa/Porto-Novo",
  "Africa/Sao_Tome", "Africa/Tripoli", "Africa/Tunis", "Africa/Windhoek",
  "America/Adak", "America/Anchorage", "America/Anguilla", "America/Antigua",
  "America/Araguaina", "America/Argentina/La_Rioja", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta",
  "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia",
  "America/Aruba", "America/Asuncion", "America/Bahia", "America/Bahia_Banderas",
  "America/Barbados", "America/Belem", "America/Belize", "America/Blanc-Sablon",
  "America/Boa_Vista", "America/Bogota", "America/Boise", "America/Buenos_Aires",
  "America/Cambridge_Bay", "America/Campo_Grande", "America/Cancun", "America/Caracas",
  "America/Catamarca", "America/Cayenne", "America/Cayman", "America/Chicago",
  "America/Chihuahua", "America/Ciudad_Juarez", "America/Coral_Harbour", "America/Cordoba",
  "America/Costa_Rica", "America/Coyhaique", "America/Creston", "America/Cuiaba",
  "America/Curacao", "America/Danmarkshavn", "America/Dawson", "America/Dawson_Creek",
  "America/Denver", "America/Detroit", "America/Dominica", "America/Edmonton",
  "America/Eirunepe", "America/El_Salvador", "America/Fort_Nelson", "America/Fortaleza",
  "America/Glace_Bay", "America/Godthab", "America/Goose_Bay", "America/Grand_Turk",
  "America/Grenada", "America/Guadeloupe", "America/Guatemala", "America/Guayaquil",
  "America/Guyana", "America/Halifax", "America/Havana", "America/Hermosillo",
  "America/Indiana/Knox", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Tell_City",
  "America/Indiana/Vevay", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indianapolis",
  "America/Inuvik", "America/Iqaluit", "America/Jamaica", "America/Jujuy",
  "America/Juneau", "America/Kentucky/Monticello", "America/Kralendijk", "America/La_Paz",
  "America/Lima", "America/Los_Angeles", "America/Louisville", "America/Lower_Princes",
  "America/Maceio", "America/Managua", "America/Manaus", "America/Marigot",
  "America/Martinique", "America/Matamoros", "America/Mazatlan", "America/Mendoza",
  "America/Menominee", "America/Merida", "America/Metlakatla", "America/Mexico_City",
  "America/Miquelon", "America/Moncton", "America/Monterrey", "America/Montevideo",
  "America/Montserrat", "America/Nassau", "America/New_York", "America/Nome",
  "America/Noronha", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem",
  "America/Ojinaga", "America/Panama", "America/Paramaribo", "America/Phoenix",
  "America/Port-au-Prince", "America/Port_of_Spain", "America/Porto_Velho", "America/Puerto_Rico",
  "America/Punta_Arenas", "America/Rankin_Inlet", "America/Recife", "America/Regina",
  "America/Resolute", "America/Rio_Branco", "America/Santarem", "America/Santiago",
  "America/Santo_Domingo", "America/Sao_Paulo", "America/Scoresbysund", "America/Sitka",
  "America/St_Barthelemy", "America/St_Johns", "America/St_Kitts", "America/St_Lucia",
  "America/St_Thomas", "America/St_Vincent", "America/Swift_Current", "America/Tegucigalpa",
  "America/Thule", "America/Tijuana", "America/Toronto", "America/Tortola",
  "America/Vancouver", "America/Whitehorse", "America/Winnipeg", "America/Yakutat",
  "Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Macquarie",
  "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera",
  "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok", "Arctic/Longyearbyen",
  "Asia/Aden", "Asia/Almaty", "Asia/Amman", "Asia/Anadyr",
  "Asia/Aqtau", "Asia/Aqtobe", "Asia/Ashgabat", "Asia/Atyrau",
  "Asia/Baghdad", "Asia/Bahrain", "Asia/Baku", "Asia/Bangkok",
  "Asia/Barnaul", "Asia/Beirut", "Asia/Bishkek", "Asia/Brunei",
  "Asia/Calcutta", "Asia/Chita", "Asia/Colombo", "Asia/Damascus",
  "Asia/Dhaka", "Asia/Dili", "Asia/Dubai", "Asia/Dushanbe",
  "Asia/Famagusta", "Asia/Gaza", "Asia/Hebron", "Asia/Hong_Kong",
  "Asia/Hovd", "Asia/Irkutsk", "Asia/Jakarta", "Asia/Jayapura",
  "Asia/Jerusalem", "Asia/Kabul", "Asia/Kamchatka", "Asia/Karachi",
  "Asia/Katmandu", "Asia/Khandyga", "Asia/Krasnoyarsk", "Asia/Kuala_Lumpur",
  "Asia/Kuching", "Asia/Kuwait", "Asia/Macau", "Asia/Magadan",
  "Asia/Makassar", "Asia/Manila", "Asia/Muscat", "Asia/Nicosia",
  "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk", "Asia/Oral",
  "Asia/Phnom_Penh", "Asia/Pontianak", "Asia/Pyongyang", "Asia/Qatar",
  "Asia/Qostanay", "Asia/Qyzylorda", "Asia/Rangoon", "Asia/Riyadh",
  "Asia/Saigon", "Asia/Sakhalin", "Asia/Samarkand", "Asia/Seoul",
  "Asia/Shanghai", "Asia/Singapore", "Asia/Srednekolymsk", "Asia/Taipei",
  "Asia/Tashkent", "Asia/Tbilisi", "Asia/Tehran", "Asia/Thimphu",
  "Asia/Tokyo", "Asia/Tomsk", "Asia/Ulaanbaatar", "Asia/Urumqi",
  "Asia/Ust-Nera", "Asia/Vientiane", "Asia/Vladivostok", "Asia/Yakutsk",
  "Asia/Yekaterinburg", "Asia/Yerevan", "Atlantic/Azores", "Atlantic/Bermuda",
  "Atlantic/Canary", "Atlantic/Cape_Verde", "Atlantic/Faeroe", "Atlantic/Madeira",
  "Atlantic/Reykjavik", "Atlantic/South_Georgia", "Atlantic/St_Helena", "Atlantic/Stanley",
  "Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Darwin",
  "Australia/Eucla", "Australia/Hobart", "Australia/Lindeman", "Australia/Lord_Howe",
  "Australia/Melbourne", "Australia/Perth", "Australia/Sydney", "Europe/Amsterdam",
  "Europe/Andorra", "Europe/Astrakhan", "Europe/Athens", "Europe/Belgrade",
  "Europe/Berlin", "Europe/Bratislava", "Europe/Brussels", "Europe/Bucharest",
  "Europe/Budapest", "Europe/Busingen", "Europe/Chisinau", "Europe/Copenhagen",
  "Europe/Dublin", "Europe/Gibraltar", "Europe/Guernsey", "Europe/Helsinki",
  "Europe/Isle_of_Man", "Europe/Istanbul", "Europe/Jersey", "Europe/Kaliningrad",
  "Europe/Kiev", "Europe/Kirov", "Europe/Lisbon", "Europe/Ljubljana",
  "Europe/London", "Europe/Luxembourg", "Europe/Madrid", "Europe/Malta",
  "Europe/Mariehamn", "Europe/Minsk", "Europe/Monaco", "Europe/Moscow",
  "Europe/Oslo", "Europe/Paris", "Europe/Podgorica", "Europe/Prague",
  "Europe/Riga", "Europe/Rome", "Europe/Samara", "Europe/San_Marino",
  "Europe/Sarajevo", "Europe/Saratov", "Europe/Simferopol", "Europe/Skopje",
  "Europe/Sofia", "Europe/Stockholm", "Europe/Tallinn", "Europe/Tirane",
  "Europe/Ulyanovsk", "Europe/Vaduz", "Europe/Vatican", "Europe/Vienna",
  "Europe/Vilnius", "Europe/Volgograd", "Europe/Warsaw", "Europe/Zagreb",
  "Europe/Zurich", "Indian/Antananarivo", "Indian/Chagos", "Indian/Christmas",
  "Indian/Cocos", "Indian/Comoro", "Indian/Kerguelen", "Indian/Mahe",
  "Indian/Maldives", "Indian/Mauritius", "Indian/Mayotte", "Indian/Reunion",
  "Pacific/Apia", "Pacific/Auckland", "Pacific/Bougainville", "Pacific/Chatham",
  "Pacific/Easter", "Pacific/Efate", "Pacific/Enderbury", "Pacific/Fakaofo",
  "Pacific/Fiji", "Pacific/Funafuti", "Pacific/Galapagos", "Pacific/Gambier",
  "Pacific/Guadalcanal", "Pacific/Guam", "Pacific/Honolulu", "Pacific/Kiritimati",
  "Pacific/Kosrae", "Pacific/Kwajalein", "Pacific/Majuro", "Pacific/Marquesas",
  "Pacific/Midway", "Pacific/Nauru", "Pacific/Niue", "Pacific/Norfolk",
  "Pacific/Noumea", "Pacific/Pago_Pago", "Pacific/Palau", "Pacific/Pitcairn",
  "Pacific/Ponape", "Pacific/Port_Moresby", "Pacific/Rarotonga", "Pacific/Saipan",
  "Pacific/Tahiti", "Pacific/Tarawa", "Pacific/Tongatapu", "Pacific/Truk",
  "Pacific/Wake", "Pacific/Wallis",
];

/** "Europe/Istanbul" → "Europe/Istanbul (GMT+3)", using the offset in effect right now. */
export function timeZoneLabel(tz: string): string {
  try {
    const offset = new Intl.DateTimeFormat("en-US", { timeZone: tz, timeZoneName: "shortOffset" })
      .formatToParts(new Date())
      .find((p) => p.type === "timeZoneName")?.value;
    return offset ? `${tz.replace(/_/g, " ")} (${offset})` : tz;
  } catch {
    return tz;
  }
}
